services:
  signal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/0
      - FLUX_URL=http://flux:3000
      - PULSE_URL=http://pulse:3000
      - REFLEX_URL=http://reflex:3000
      - RECALL_URL=http://recall:3000
      - SIGNAL_URL=http://localhost:3006
    volumes:
      - .:/rails
      - ../brainzlab-sdk:/brainzlab-sdk
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
      - redis
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bin/rails db:prepare && bin/rails server -b 0.0.0.0"

  signal_worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/0
      - FLUX_URL=http://flux:3000
      - PULSE_URL=http://pulse:3000
      - REFLEX_URL=http://reflex:3000
      - RECALL_URL=http://recall:3000
    volumes:
      - .:/rails
      - ../brainzlab-sdk:/brainzlab-sdk
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
      - redis
      - signal
    command: bash -c "bundle install && bundle exec sidekiq"

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6386:6379"

volumes:
  postgres_data:
  bundle_cache:
